### ISSUE TITLE
Support scalable vector icons & patterns

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-style-spec#222]
There's only mention of .png in the spec when talking about sprites. Can we support vector sprite formats like SVG? I would never want to use a bitmap as my sprite source what with the current state of device screen resolution.

**Comment by 1ec5** [comment]
@samanpwbb clarified in chat that the main use case for the feature described in this issue is to have a style image scale cleanly using `icon-size`, whereas multiple screen resolutions can already be supported via separate `@1x` and `@2x` sprite sheets.

#581 is a related idea about leveraging the tooling around nine-part images that’s present on all the native platforms. Highway shields would benefit from either feature.

**Comment by lucaswoj** [comment]
Closing this as a "wontfix" for now. We can open a new ticket if there's a newfound pressing need or implementation concept.
