### ISSUE TITLE
Provide "fill-stroke-*" properties and rename "fill" to "polygon"

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#223]
Pros:
- An SVG-like "polygon" type layer that supports both stroke and fill is how style authors expect and want things to work (see e.g. #221, #217, #218)
- `fill-outline-color` is a hack (#199)

Cons:
- Performance concerns?

**Comment by ansis** [comment]
I agree that we should kill `fill-outline-color` (#199). It's confusing. We can make up the performance by optimizing line tessellation more, or if that still isn't fast enough we could draw lines with `"line-join": "butt"` the same way the antialiasing edge for fills is drawn.

I'm not convinced that we should add a polygon type though.
- all the line-* properties would need to be duplicated as stroke-* properties
- the performance cost of create a stroke would be less clear than when it is a separate layer
- if strokes are kept separate it is easier to re-arrange the z order
- having a ton of new properties for fill layers could make UIs more cluttered

It is tedious to create a second layer for the stroke with the same data as the fill layer. A polygon type *would* fix this. But maybe it could be fixed by adding a way to [reference other layer's data](https://gist.github.com/ansis/d59f55c924d8f4c45232), or maybe by letting UIs handle it with an "add line" button for fill layers.

If we add a SVG-like polygon, would we add SVG-like lines with strokes and fills too?

This reminds me of the idea to allow a single layer to have multiple types, which could feel a bit more like carto. For example, `"type": ["fill", "line", "symbol"]` would let you use properties for all three. I suggested this way back in https://github.com/mapbox/mapbox-gl-js/issues/244, but maybe for the wrong reasons. @yhahn talked me out of thinking it was a good idea. It came up again in https://github.com/mapbox/mapbox-gl-js/issues/356 and https://github.com/mapbox/mapbox-gl-style-spec/issues/9 and https://github.com/mapbox/mapbox-gl-style-spec/issues/27

**Comment by nickidlugash** [comment]
@ansis @jfirebaugh @mourner Can we address this for `v8`?

**Comment by jfirebaugh** [comment]
This is out of scope for v8 -- we don't have a good lead on implementing it and it's lower priority than other features that are not currently planned for v8 like data-driven styles.

**Comment by nickidlugash** [comment]
Ok, but I'm pretty hesitant for us to launch the app with the [`fill-outline-color`](https://github.com/mapbox/mapbox-gl-style-spec/issues/240) still implemented.

**Comment by incanus** [comment]
https://github.com/mapbox/mapbox-gl-native/issues/1737

**Comment by lucaswoj** [comment]
@mourner Is this easier to do with earcut?

**Comment by mourner** [comment]
@lucaswoj probably not related much.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4087

**Comment by brunoabinader** [comment]
As part of Qt integration, providing `fill-stroke-width` would enable Qt's [MapRectangle border width property](http://doc.qt.io/qt-5/qml-qtlocation-maprectangle.html#border.width-prop) conversion.
