### ISSUE TITLE
Prerendered layer type: keep or kill

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-style-spec#232]
Let's talk about this.

@nickidlugash you rewrote outdoors with terrain-v2 — what are your thoughts on this?

@ansis @kkaefer I remember talking about the potential for prerendered layers to serve as sort of fallback layers in slow styles or renderers. Does this make sense at all/still seem like a possibility? For anything but blurred layers, they look pretty awful unless you draw them at really large raster sizes, which isn't an especially perf-friendly trick.

cc @jfirebaugh @mourner @tmcw @edenh

**Comment by ansis** [comment]
> I remember talking about the potential for prerendered layers to serve as sort of fallback layers in slow styles or renderers. Does this make sense at all/still seem like a possibility?

No, I don't think so. It would be great if we could kill them by not needing blur, or by faking blur some other way.

**Comment by nickidlugash** [comment]
@lbud the main reason I removed the pre-rendered layer from outdoors was because the blur only takes literal values, not functions/ramps, and having the same level of blurring on all zoom levels was overall worse than having no blur at all (normally it makes sense to increase blur as zoom level increases). With the old terrain (where, on top of GL overzooming, the polygons were not as detailed to begin with), the blurring helped a bit to hide the overly-simple polygons. In terrain v2, the polygons are more detailed so this is much less necessary.

Are we at all still thinking about [implementing functions/ramps for layout properties](https://github.com/mapbox/mapbox-gl-js/issues/361)? If we are, the ability to blur *could* potentially be useful. However, as @lbud mentioned, prerendered layers look pretty bad without a blur, so if we were transitioning from no blur to some blur, I'm guessing that the zoom levels with no blur will not look good.

I guess if someone was making a map that was very limited in zoom levels, then the current blur functionality could be useful, but personally I don't find it useful.

**Comment by mourner** [comment]
:+1: for killing off prerendered layers and not worrying about blur, terrain-v2 looks good without it. Lets worry about performance instead.

**Comment by ljbade** [comment]
From discussion with @nickidlugash

I would like to test the performance of pre-rendered vs live rendered V2 on older Android devices that have a slower GPU to make sure they can run the new outdoors style fast enough.

I note that Google use pre-rendered terrain in the Android app.

**Comment by edenh** [comment]
:+1: for killing. As data density improves for vector sources, the need for this is diminishing.

**Comment by jfirebaugh** [comment]
Agreed. We'll remove this for v7.
