### ISSUE TITLE
Scale halo-width to font-size

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-style-spec#239]
Analogous to how we're scaling `line-dasharray` to `line-width`

Halos that look good at high zooms

![screen shot 2015-01-23 at 11 13 53 am](https://cloud.githubusercontent.com/assets/4551508/5880989/be73ed56-a2f1-11e4-9392-948dc20847e5.png)

Are often too fat at low zooms

![screen shot 2015-01-23 at 11 14 00 am](https://cloud.githubusercontent.com/assets/4551508/5880995/cec31fb0-a2f1-11e4-854e-0ad9409b96c0.png)

I can't think of a use case where I'd use a size-independent halo width-- anyone else?

**Edit**: and while we're at it, icon-size and icon-halo, too

cc/ @kkaefer @ansis @nickidlugash

**Comment by peterqliu** [comment]
My rule of thumb (donning my `art school hat` here) is that measurements *within* a label (letter-spacing, line-height, halo) falls within the typography realm, and needs to scale with text size to be kosher. However, measurements positioning the label on the greater map (padding, rotation, translation) is cartography, and can be done in pixels/degrees.

**Comment by nickidlugash** [comment]
hmm, I have to disagree here. The majority of the time, I don't think of halos as a "feature" of a label, per se, but just a technique to make a label more visible/legible. Consequently, my tactic is often to make the halo as minimal as possible (whether that means size, color, opacity, blur) while still accomplishing this goal, and this often means that my halo styling is not relative to the text-size. In fact, I often style halo-size with a literal value, not a ramp, because I find that the optimum value for all zoom levels is practically the same.

Personally I'd much rather work with `px` for halo size (and blur), but would be curious if anyone else had an opinion.

**Comment by jfirebaugh** [comment]
Let's keep the status quo here.
