### ISSUE TITLE
Decrease default value for "symbol-min-distance"

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-style-spec#245]
Line label density improved with https://github.com/mapbox/mapbox-gl-js/pull/989 but density could be increased further by having a smaller default `symbol-min-distance` value. The current default is 250 pixels.

What would be a better default value? or is 250 fine?

@nickidlugash @edenh @peterqliu

**Comment by mourner** [comment]
We could also make it a function of zoom now.

**Comment by ansis** [comment]
or the units for the property could be em instead of pixels

**Comment by nickidlugash** [comment]
I think `symbol-min-distance` is more correlated to zoom level than to text size, so a function might work, although keeping it a literal number might be the most user-friendly, since either way I think users are going to have to adjust this value relatively frequently. 

Here's what seem to be pretty good values for a few Streets layers (at least for Outdoors style):

- road_label: 
```
{
  "base": 0.6,
  "stops": [[12, 50], [18, 250]]
}
```

- contour_label:
```
{
  "base": 0.6,
  "stops": [[11, 150], [18, 250]]
}
```

- marine_label:
```
{
  "base": 0.6,
  "stops": [[2, 50], [6, 250]]
}
```

^ The optimal value for marine labels are quite different than roads/contours because of the zoom levels that they're visible at. My instinct is to optimize the default value for labels similar to road labels – aka mid-to-long labels at mid-to-high zoom levels.  

@peterqliu @edenh have you guys had a chance to play around with label density for other data layers?

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4101
