### ISSUE TITLE
Remove "fill-antialias" property

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-style-spec#289]
`fill-antialias` is useless. Theoretically you could disable antialiasing to get a tiny performance improvement if the fill edges are covered by something else (a thick line outline). In practice the performance improvement is insignificant.

**Comment by nickidlugash** [comment]
@ansis Want to add to [v8](https://github.com/mapbox/mapbox-gl-style-spec/pull/264)?

**Comment by ansis** [comment]
added

**Comment by kkaefer** [comment]
> In practice the performance improvement is insignificant.

Not sure about this. Do you have any numbers? I've seen performance boosts for detailed polygons, like forest areas.

**Comment by ansis** [comment]
nope, I don't have any numbers. I was guessing that since the property could be used without visual defects in only a very small number of cases it wouldn't have any big impact on total performance.

I have a hard time imagining anyone actually using this property in a style, so I don't think we should have it in the editor or spec.

I'm fine with keeping it if you think people will actually use it.

**Comment by jfirebaugh** [comment]
This doesn't block app, right? If so let's not change it in v8.

**Comment by ajashton** [comment]
When dealing with transparent overlapping shapes and subtle color shifts the aliased polygons tend to actually look better (especially on hidpi). We have fill-antialias disabled in hillshading layers for several styles to avoid problems with overlapping transparency (note both the seams due to lack of buffers and the darker outline around the full outline of each hillshade polygon):

![screenshot from 2017-01-24 20 57 11](https://cloud.githubusercontent.com/assets/126952/22275038/d6022a2e-e277-11e6-954a-c842cb5e2bb8.png)

I would also like to see some numbers re: performance on some dense layers such as hillshading and landuse.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4093
