### ISSUE TITLE
text-rotation should be interpolated, not piecewise-constant

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-style-spec#306]
Rotation should tween between zoom values.

**Comment by jfirebaugh** [comment]
Making `text-rotate` an interpolated property would mean that we'd need to redo text placement on every zoom change. We currently redo placement on every rotation change and it's reasonably performant, so maybe this is ok. cc @ansis 

This would also make `text-rotate` the first interpolated layout property, which adds some complexity.

Is there a real-world use case for this?

**Comment by ansis** [comment]
I'd rather not have it redo placement on zoom change. Labeling is designed so that labels do not jump around much while zooming. Redoing every time zoom changes would break that.

Since needing to smoothly change `text-rotate` seems really rare, I'd rather not make big changes to implement it.

We could eventually make it a dual paint/layout property similar to `text-size` (#255) so that the actual rendered text's rotation is interpolated but collision placement only happens at whole zoom levels.

Unless it's causing problems elsewhere, I'd like to leave it as is for now and maybe come back to it after #255.

**Comment by jfirebaugh** [comment]
I'm assuming the use case here is "flashy but impractical rotate effect on zoom". Closing for now.

**Comment by tmcw** [comment]
This is actually a bug because [the current style spec represents text-rotate as interpolated](https://github.com/mapbox/mapbox-gl-style-spec/blob/6719860a4010c57b846ac69597a4ccb8112ca64e/reference/v7.json#L545).

**Comment by jfirebaugh** [comment]
Actually I think `interpolated` in the style spec was correct, and [my comment above](https://github.com/mapbox/mapbox-gl-style-spec/issues/306#issuecomment-116848370) was partially incorrect.

Numeric layout properties *can* support `interpolated` functions, and `text-rotate` is far from the only example. It's just that the functions are only ever evaluated at integer zoom levels.

**Comment by jfirebaugh** [comment]
Next actions here would be to revert https://github.com/mapbox/mapbox-gl-style-spec/pull/319 and add some text to https://www.mapbox.com/mapbox-gl-style-spec/#function explaining how evaluation of layout property functions works.

**Comment by tmcw** [comment]
@jfirebaugh for my usecase - which consists of "showing a chart in a ui that visualizes how things are interpolated", text will not be good enough: we need a programmatic, explicit hint that tells us whether something is interpolated or not.

**Comment by jfirebaugh** [comment]
@tmcw - `text-rotation` is interpolated. That's captured in the spec with `"function": "interpolated"`. And then from the fact that `text-rotation` is a layout property, you can deduce that it's evaluated only at integer zoom levels.

**Comment by jfirebaugh** [comment]
Reverted in b97ba5aa7d3ae94e9871a7956559049a9cd6fa18.
