### ISSUE TITLE
Drop constants and color-ops from v8

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-style-spec#308]

**Comment by jfirebaugh** [comment]
Deep breath. Constants are gone from the editor. Do we want to drop them from the spec and renderers?

**Comment by lucaswoj** [comment]
Just had a good chat with @tmcw, @nickidlugash, and others about this.

It sounds like there's a good case for removing constants **and color ops** from the v8 spec because

 - app doesn't support constants or color-ops
 - the current implementation of color-ops hasn't been tested in the wild ("unused code is broken by default") 
 - changing the spec for color-ops after they have been released would create headaches
 - removing / restoring color-ops from gl-js or gl-native only involves [~10 LOC](https://github.com/mapbox/mapbox-gl-js/blob/v8/js/style/style_declaration.js#L94)
 - we don't want to lose any information when importing / exporting styles from app (i.e. if color-ops were in the spec but not supported in app)

**Comment by lucaswoj** [comment]
Ref https://github.com/mapbox/mapbox-gl-style-spec/issues/38

**Comment by lucaswoj** [comment]
I think the right way forward is to remove both constants and color-ops from v8. We might want to work them into a future release.

**Comment by lucaswoj** [comment]
We'll need to back out these changes:

> * color operations https://github.com/mapbox/mapbox-gl-style-spec/issues/38
>   * JS https://github.com/mapbox/mapbox-gl-js/pull/1158
>   * Native https://github.com/mapbox/mapbox-gl-native/pull/1311
>   * Spec https://github.com/mapbox/mapbox-gl-style-spec/pull/271

**Comment by mb12** [comment]
@jfirebaugh What is the reason for this change? Does that mean we have to start inlining a  constant that is used in multiple places in the style.json?  For e.g. it is better to refer to a constant like  this via a meaningful name rather than inline it. 
```
    "@motorway_casing_width": {
      "base": 1.2,
      "stops": [[5, 0.4], [6, 0.6], [7, 1.5], [20, 22]]
    },
```

**Comment by jfirebaugh** [comment]
@mb12 We are keeping the style spec tightly focused around the core features needed by the renderers and by our online style editor (launching publicly soon). Constants don't fall into either of those categories. If you are editing styles by hand and want to use constants, you can use a preprocessing step with a tool like https://github.com/screee/screess.
