### ISSUE TITLE
pattern fill scaling options API

### ISSUE THREAD

**Issue by kelvinabrokwa** [mapbox/mapbox-gl-style-spec#398]
re: https://github.com/mapbox/mapbox-gl-js/issues/1831

This morning I made a small adjustment that allows you to choose between rescaling at integer zoom levels (how it currently works)

![image2](https://cloud.githubusercontent.com/assets/7795202/12101784/6f1d16be-b2eb-11e5-8d61-ed5f19ded43d.gif)

and keeping the image at 1x at all times.

![image](https://cloud.githubusercontent.com/assets/7795202/12101781/6928fec6-b2eb-11e5-8b4e-a7b800e0476d.gif)

@samanpwbb @nickidlugash ideas on how the user will be able to switch between these options? Default behaviour?

/cc @samanpwbb @nickidlugash @lucaswoj @ansis

**Comment by samanpwbb** [comment]
Can you either use really high FPS gifs or videos to show the different approaches off? it's hard to tell from above what exactly is going on.

Could just be the gif, but integer zoom scaling should be smoother than what's in your gif. I think, if we do want to keep scaled patterns around, they should be tweaked either so the map always uses retina assets for pattersn _or_ the map only downscales and never upscales images (or upscales images much less).

The 1x image looks really disorienting because of how the pattern is moving around.

**Comment by lucaswoj** [comment]
We can fix the position jumpiness with layer-by-layer rendering :smile:

**Comment by lucaswoj** [comment]
The important things to discuss in this ticket are
- what scaling modes we want to support 
- what syntax we will use to specify them

**Comment by samanpwbb** [comment]
> ideas on how the user will be able to switch between these options? 

Sure, either this should be a new style property in the style spec, like `fill-pattern-scale` that takes a `boolean` value and defaults to true. Or we just pick the one best one as a default and do nothing else.

**Comment by nickidlugash** [comment]
>  this should be a new style property in the style spec, like fill-pattern-scale that takes a boolean value and defaults to true. Or we just pick the one best one as a default and do nothing else.

I _think_ we should just set this as not scaling – I'm not seeing much advantage to the scaled option once layer-by-layer rendering lands. @samanpwbb can you think of use cases where scaling would be preferable?

**Comment by nickidlugash** [comment]
Er, I guess scaling could be useful if you want to use different size patterns for integer zoom levels, and you want to seamless transition between the two? Maybe? But that would only be for patterns that increase in size at the same rate as tiles.

**Comment by lucaswoj** [comment]
Closing as stale
