### ISSUE TITLE
Remove "*-ignore-placement" properties and expand the scope of "*-allow-overlap" properties

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-style-spec#429]
There are currently two properties that affect how a symbol
- `-allow-overlap` determines if previous symbols affect the placement of the current symbol
- `-ignore-placement` determines if the current symbol will affect the placement of layer symbols

In most cases you want both to have the same value. I can't think of an example you would want them to be different.

**We should remove -ignore-placement and make -allow-overlap do what both these properties currently do.**

@nickidlugash @peterqliu can you imagine a case where you would want these two properties to be separate?

**Comment by nickidlugash** [comment]
@ansis – @peterqliu has probably touched upon more varied styling use cases, but personally I don't have any important use cases for having different values for these two properties. I'm a fan of reducing the number of arcane properties pertaining to label placement/behavior :+1: 

Not to open a can of worms, but this is what I actually want for collision properties (actual property names TBD):
1. Allow overlap with symbols in other layers
2. Allow overlap within symbols in current layer

I think the distinction between whether a symbol can overlap symbols within its own layer or with symbols in other layers is much more important for styling than the distinction between whether a symbol can overlap symbols in layers above or below the current layer. Since collision detection is per-feature, both our current properties essentially create identical behavior for symbols within the same layer (a `true` value for either makes symbols within a layer overlap each other). I think this has been the source of a lot of user confusion between the two properties. We have two properties to control overlapping symbols, but you still can't control what you actually want to control.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4117
