### ISSUE TITLE
Labeling offset lines

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-style-spec#437]
There's no good way to offset labels to track their corresponding lines, at the moment. Two obstacles:
- Units (minor): line-offset is in `px`, while text-offset is in `em`s
- Frame of reference (major): line-offset is relative to the line's direction, while text-offset is relative to the map or viewport. Depending on direction, the two can get offset in opposite directions:

<img width="545" alt="screen shot 2016-03-30 at 7 28 11 pm" src="https://cloud.githubusercontent.com/assets/4551508/14163796/c2535072-f6ad-11e5-9fdf-cef846def505.png">

**Comment by ansis** [comment]
the second issue came up here: https://github.com/mapbox/mapbox-gl-js/issues/2350 I think it's something we can fix. Unfortunately text-offset doesn't work nicely with curved lines. If you add a high offset on a curved line you'll see what I mean. The characters will either bunch up or spread out. I'm not sure how fixable that problem is.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4112
