### ISSUE TITLE
Add note on fill-color that its alpha channel doesn't matter when using extrusions

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-style-spec#556]
We have a note here

![2016-11-02 at 5 46 pm](https://cloud.githubusercontent.com/assets/32314/19948690/4c5c9f96-a124-11e6-8529-556370dc26c4.png)

But need one here

![2016-11-02 at 5 46 pm](https://cloud.githubusercontent.com/assets/32314/19948699/595907a2-a124-11e6-85c4-742ee2942d14.png)

There's precedent, too, since we have a note that fill-color doesn't affect 1px strokes.

**Comment by lbud** [comment]
Not needed in light of https://github.com/mapbox/mapbox-gl-style-spec/issues/554. When the new documentation is published this should be clear: 
https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/reference/v8.json#L1749 

> ```
> "fill-extrusion-color": {
>   "doc": "The base color of the extruded fill. The extrusion's surfaces will be shaded differently based on this color in combination with the root `light` settings. If this color is specified as `rgba` with an alpha component, the alpha component will be ignored; use `fill-extrusion-opacity` to set layer opacity.",
> ```

https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/reference/v8.json#L1738

> ```
> "fill-extrusion-opacity": {
>   "doc": "The opacity of the entire fill extrusion layer. This is rendered on a per-layer, not per-feature, basis."
> ```

Please reopen if you think they should be clearer; otherwise, docs will be republished with the (tomorrow?) release of gl-js v0.27.0.
