### ISSUE TITLE
Questions about property- and property-zoom functions

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-style-spec#586]
I'm trying to build a first-draft UI for these in Studio and ran into a few questions. I didn't find answers in the style spec docs, so I'm thinking that maybe when I have answers I'll try to add them to the docs:

- Is there a minimum number of stops for property- or property-zoom functions? (Or zoom functions for that matter. I know in Studio we're enforcing a minimum of two, but does the spec require that?)
- How do you set a *fallback* property value? I suppose with any interpolatable property you could interpolate every necessary value as long as you have two stops to create a function with (^^). But for non-interpolatable properties, you'd be in a pickle. For example, let's say your reference field is a string field like `name`, and you don’t provide a stop for every possible value: how can you control what happens when `name` does not match a stop? I want "Mexico" to be red, "Canada" to be purple, and everything else to be pink.
- In the style-spec JSON itself, does `property-function: true` mean *both* property-function and property-zoom-function, or do no properties have property-zoom-function support yet?

**Comment by davidtheclark** [comment]
cc @mapbox/appbox

**Comment by jfirebaugh** [comment]
> Is there a minimum number of stops for property- or property-zoom functions?

The minimum is 1. This is [enforced by the validator](https://github.com/mapbox/mapbox-gl-style-spec/blob/873f61aa18697ca93ad20be19f75c188cec863a8/lib/validate/validate_function.js#L59-L61).

> How do you set a fallback property value?

I filed #582 related to this, and #480 is also related.

> Does `property-function: true` mean both property-function and property-zoom-function

Yes. Note that you can't really rely on this property for anything meaningful because it indicates which properties could _conceivably_ someday support data-driven functions, not which ones actually do. I think we should probably remove it in favor of `sdk-support['data-driven styling']`.

**Comment by davidtheclark** [comment]
> I think we should probably remove it in favor of sdk-support['data-driven styling']

If `'data-driven styling'` is supported, then, it will favor both types of functions, right?

**Comment by jfirebaugh** [comment]
Correct.
