### ISSUE TITLE
Provide "line-stroke-*" properties

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-style-spec#637]

**Comment by jfirebaugh** [comment]
If we add these, we should remove `line-gap-width`.

**Comment by nickidlugash** [comment]
> If we add these, we should remove line-gap-width.

@jfirebaugh @lucaswoj can you please elaborate on why we should do this?

**Comment by jfirebaugh** [comment]
Because it's equivalent functionality -- you can replace a pair of fill and casing layers with a single layer with both fill and stroke, or a standalone gapped line with a like with a stroke and transparent fill.

If we don't also remove `line-gap-width`, then we are adding complexity to the renderer without meaningfully expanding its functionality. I would oppose `line-stroke-*` in that case.

**Comment by nickidlugash** [comment]
Ok, that makes sense. I misunderstood this ticket and thought we were just renaming `line-` to be `line-stroke`.

> you can replace a pair of fill and casing layers with a single layer with both fill and stroke

Just noting that you _will_ still need two layers to create a fill and casing, since they need to be drawn in different parts of the drawing order. However, overall, this will still be more convenient then the current system because the `line-width` for both the fill and casing will be identical, whereas currently the `line-gap-width` of the casing is equal to the `line-width` of the fill.

**Comment by lucaswoj** [comment]
This issue was moved to mapbox/mapbox-gl-js#4162
